"""Generate include/FlickImGuiMap.h - FLICK's ImGui 1.92 numbers translated BY NAME into the ImGui 1.90.8 AMF embeds.

FLICK consumers are built against ImGui 1.92 (powerof3's fork, fbbe3efd - extern/imgui-1.92/imgui.h) and pass enum values
and flag words through FLICK's API as plain ints. AMF draws with 1.90.8, where many of those numbers mean something else
(logic library 29: a passed-through index tints the wrong colour silently). Every value is translated by its NAME:
  - index enums (ImGuiCol_, ImGuiStyleVar_, ImGuiKey_, ImGuiDir, ImGuiMouseButton_, ImGuiMouseCursor_): a table from the
    1.92 value to the 1.90 value, -1 where 1.90 has no such name;
  - flag families (ImGuiWindowFlags_, ImGuiTreeNodeFlags_ ...): one row per single-bit 1.92 flag, with the 1.90 bit of the
    same name or 0 where 1.90 has none (the bit is dropped, and the log can say which).
Usage: python tools/gen-flick-imgui-map.py   (rewrites include/FlickImGuiMap.h; deterministic)
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NEW = os.path.join(ROOT, "extern", "imgui-1.92", "imgui.h")
# the 1.90.8 header AMF really compiles with is vcpkg's (source/cimgui/imgui/imgui.h only forwards to it)
OLD = next((os.path.join(ROOT, "build", d, "vcpkg_installed", "x64-windows-static-md", "include", "imgui.h")
            for d in ("relwithdebinfo-se-only", "relwithdebinfo-17")
            if os.path.exists(os.path.join(ROOT, "build", d, "vcpkg_installed", "x64-windows-static-md", "include", "imgui.h"))), None)
OUT = os.path.join(ROOT, "include", "FlickImGuiMap.h")

INDEX_ENUMS = ["ImGuiCol_", "ImGuiStyleVar_", "ImGuiKey", "ImGuiDir", "ImGuiMouseButton_", "ImGuiMouseCursor_"]
FLAG_ENUMS = ["ImGuiWindowFlags_", "ImGuiChildFlags_", "ImGuiInputTextFlags_", "ImGuiTreeNodeFlags_", "ImGuiPopupFlags_",
              "ImGuiSelectableFlags_", "ImGuiComboFlags_", "ImGuiTabBarFlags_", "ImGuiTabItemFlags_", "ImGuiFocusedFlags_",
              "ImGuiHoveredFlags_", "ImGuiDragDropFlags_", "ImGuiButtonFlags_", "ImGuiColorEditFlags_", "ImGuiSliderFlags_",
              "ImGuiTableFlags_", "ImGuiTableColumnFlags_", "ImGuiTableRowFlags_", "ImGuiCond_", "ImGuiConfigFlags_"]


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse_enums(path):
    """{enum name: [(member, value)]} for every `enum Name ... { ... };` block, values evaluated in order."""
    text = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    # the preprocessor branch for the obsolete names is kept: a mod may still use a name 1.92 keeps under that macro
    text = re.sub(r"^\s*#.*$", "", text, flags=re.M)
    out = {}
    known = {}
    for m in re.finditer(r"\benum\s+(\w+)\s*(?::\s*\w+\s*)?\{(.*?)\};", text, flags=re.S):
        name, body = m.group(1), m.group(2)
        members = []
        value = -1
        for raw in body.split(","):
            item = raw.strip()
            if not item:
                continue
            if "=" in item:
                member, expr = (s.strip() for s in item.split("=", 1))
                py = expr
                for k in sorted(known, key=len, reverse=True):
                    py = re.sub(r"\b%s\b" % re.escape(k), str(known[k]), py)
                py = re.sub(r"(\d+)[uU]\b", r"\1", py).replace("(int)", "")
                try:
                    value = int(eval(py, {"__builtins__": {}}))
                except Exception:
                    continue   # an expression this generator cannot read - left out, so it is never mistranslated
            else:
                member = item
                value += 1
            if not re.fullmatch(r"\w+", member):
                continue
            known[member] = value
            members.append((member, value))
        out[name] = members
    return out, known


def family(members_by_enum, prefix):
    for name, members in members_by_enum.items():
        if name.rstrip("_") == prefix.rstrip("_"):
            return members
    return []


def main():
    new_enums, new_known = parse_enums(NEW)
    old_enums, old_known = parse_enums(OLD)
    lines = []
    w = lines.append
    w("#pragma once")
    w("")
    w("// GENERATED by tools/gen-flick-imgui-map.py - do not edit. FLICK consumers' ImGui 1.92 numbers (powerof3/imgui fbbe3efd,")
    w("// extern/imgui-1.92/imgui.h) translated BY NAME into the ImGui 1.90.8 AMF draws with. -1 / 0 = no such name in 1.90.")
    w("")
    w("#include <cstdint>")
    w("")
    w("namespace flick::imgui_map")
    w("{")
    w("\tstruct FlagBit { std::uint32_t newBit; std::uint32_t oldBit; const char* name; };")
    w("")
    for prefix in INDEX_ENUMS:
        nm = family(new_enums, prefix)
        om = {k: v for k, v in family(old_enums, prefix)}
        rows = [(m, v) for m, v in nm if not m.endswith("_COUNT") and v >= 0 and v < 4096]
        if not rows:
            continue
        size = max(v for _, v in rows) + 1
        table = [-1] * size
        for m, v in rows:
            if m in om:
                table[v] = om[m]
        ident = prefix.rstrip("_").replace("ImGui", "")
        w(f"\t// {prefix}: {sum(1 for t in table if t >= 0)} of {len(rows)} names exist in 1.90")
        w(f"\tinline constexpr int k{ident}Size = {size};")
        body = ", ".join(str(t) for t in table)
        w(f"\tinline constexpr short k{ident}[k{ident}Size] = {{ {body} }};")
        w("")
    for prefix in FLAG_ENUMS:
        nm = family(new_enums, prefix)
        om = {k: v for k, v in family(old_enums, prefix)}
        rows = []
        for m, v in nm:
            if v <= 0 or (v & (v - 1)) != 0:
                continue   # combinations and zero are rebuilt from the single bits
            rows.append((v, om.get(m, 0) if (om.get(m, 0) & (om.get(m, 0) - 1)) == 0 else 0, m))
        if not rows:
            continue
        ident = prefix.rstrip("_").replace("ImGui", "")
        w(f"\tinline constexpr FlagBit k{ident}[] = {{")
        for v, o, m in rows:
            w(f"\t\t{{ 0x{v:X}u, 0x{o:X}u, \"{m}\" }},")
        w("\t};")
        w("")
    w("\t// A 1.92 flag word -> the 1.90 word; a_dropped gets the bits 1.90 has no name for.")
    w("\ttemplate <std::size_t N>")
    w("\tconstexpr std::uint32_t Flags(std::uint32_t a_new, const FlagBit (&a_map)[N], std::uint32_t* a_dropped = nullptr)")
    w("\t{")
    w("\t\tstd::uint32_t out = 0, dropped = 0, seen = 0;")
    w("\t\tfor (const FlagBit& b : a_map)")
    w("\t\t{")
    w("\t\t\tif ((a_new & b.newBit) == 0) { continue; }")
    w("\t\t\tseen |= b.newBit;")
    w("\t\t\tif (b.oldBit) { out |= b.oldBit; } else { dropped |= b.newBit; }")
    w("\t\t}")
    w("\t\tdropped |= a_new & ~seen;")
    w("\t\tif (a_dropped) { *a_dropped = dropped; }")
    w("\t\treturn out;")
    w("\t}")
    w("")
    w("\t// A 1.92 index -> the 1.90 index (-1 = none).")
    w("\ttemplate <std::size_t N>")
    w("\tconstexpr int Index(int a_new, const short (&a_map)[N]) { return a_new >= 0 && a_new < static_cast<int>(N) ? a_map[a_new] : -1; }")
    w("}")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("wrote", OUT)
    for prefix in INDEX_ENUMS + FLAG_ENUMS:
        print(f"  {prefix:24} 1.92: {len(family(new_enums, prefix)):4}  1.90: {len(family(old_enums, prefix)):4}")


if __name__ == "__main__":
    main()
