"""Generate include/FlickSlots.inc - the order and C types of FLICK's 259 API slots, in AMF's own type names.

FLICK host plan section 3 / 13 (4. plans\\amf-flick\\PLAN.md): AMF answers FLICK's C table, so it must declare the slots in
exactly FLICK's order with exactly their parameter types - x64 passes a float in an XMM register and an int in a general
one, so a wrong type is a wrong value with no error. This script reads ONLY the declarations in the public API header's
`struct FUCK_Interface` (interface fact, needed to interoperate) and writes them as an X-macro list:

    FLICK_SLOT(<return type>, <name>, (<parameter types>))

with FLICK's own types renamed to AMF's (FUCK::ITool* -> flick::Tool*, ImFont* -> void* (AMF hands out font tokens),
FLICK's enums -> int, the SimpleIni reference -> void*). No function bodies, widget code or styles are read or copied.
The header is not vendored into AMF: point this at the plans folder's copy when regenerating.

Run from the repo root:
    python tools/gen-flick-slots.py "..\\..\\4. plans\\amf-flick\\api\\FUCK_API.h"
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "include", "FlickSlots.inc")

TYPE_MAP = [
    (r"\bFUCK::ITool\s*\*", "flick::Tool*"),
    (r"\bFUCK::IWindow\s*\*", "flick::Window*"),
    (r"\bFUCK::ManagedHotkey\s*\*", "flick::Hotkey*"),
    (r"\bFUCK_SIMPLEINI_TYPE\s*&", "void*"),
    (r"\bImFont\s*\*", "void*"),
    (r"\bFUCK::(Font|Overlay|Modifier|ItemFlags|InputDevice)\b", "int"),
    (r"\bFUCK::BindResult\b", "int"),
    (r"\bImGuiCol\b", "int"),
    (r"\bImGuiStyleVar\b", "int"),
    (r"\bImGuiKey\b", "int"),
]


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    text = open(sys.argv[1], encoding="utf-8").read()
    m = re.search(r"struct FUCK_Interface\s*\{(.*?)\n\};", text, re.S)
    if not m:
        sys.exit("struct FUCK_Interface not found")
    body = m.group(1)
    version = re.search(r"#define FUCK_API_VERSION (\d+)", text).group(1)
    slots = []
    section = ""
    for raw in body.split("\n"):
        line = raw.strip()
        if line.startswith("//"):
            section = line[2:].strip()
            continue
        if not line or line.startswith("unsigned int version"):
            continue
        sm = re.match(r"(.+?)\(\*(\w+)\)\((.*)\);$", line)
        if not sm:
            sys.exit("unparsed slot line: " + line)
        ret, name, params = sm.group(1).strip(), sm.group(2), sm.group(3).strip()
        for pat, rep in TYPE_MAP:
            ret = re.sub(pat, rep, ret)
            params = re.sub(pat, rep, params)
        # parameter names out, so the list is types only (a function-pointer parameter keeps its own parameter list)
        params = re.sub(r"\(\*\w+\)", "(*)", params)
        parts, depth, cur = [], 0, ""
        for ch in params:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append(cur.strip()); cur = ""
            else:
                cur += ch
        if cur.strip():
            parts.append(cur.strip())
        clean = []
        for p in parts:
            if "(*)" in p:
                clean.append(p)
                continue
            p = re.sub(r"\s*\[\d*\]$", "*", p)               # float[3] -> float*
            pm = re.match(r"^(.*[\*&])\s*(\w+)$", p)          # "const char* pluginName" -> "const char*"
            if pm:
                p = pm.group(1)
            else:
                vm = re.match(r"^((?:const\s+)?(?:unsigned\s+)?[\w:]+)\s+(\w+)$", p)   # "bool opening" -> "bool"
                if vm and vm.group(2) not in ("int", "char", "long", "short"):
                    p = vm.group(1)
            clean.append(p)
        slots.append((section, ret, name, ", ".join(clean)))
    with open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("// GENERATED by tools/gen-flick-slots.py from the FLICK API header (version %s) - do not edit.\n" % version)
        f.write("// FLICK_SLOT(return type, name, (parameter types)) in the C table's order; %d slots.\n" % len(slots))
        f.write("#define FLICK_API_VERSION_ANSWERED %s\n" % version)
        f.write("#define FLICK_SLOT_COUNT %d\n" % len(slots))
        last = None
        for section, ret, name, params in slots:
            if section != last:
                f.write("// %s\n" % section)
                last = section
            f.write("FLICK_SLOT(%s, %s, (%s))\n" % (ret, name, params))
    print("wrote", OUT, len(slots), "slots, version", version)


if __name__ == "__main__":
    main()
