"""Generate source/McmCategoryRules.inc - AMF's MCM auto-sort rules - from MO2 Modlist Manager's name table.

The owner, 2026-10-05: "an auto sort function which sorted the imported menus into categories, sort of like our mod
manager plugin but built into AMF. And it can just sort by name, it doesn't have to be perfect." So the rules are not
invented here: they are MO2 Modlist Manager's TEXT_SIGNALS (our own plugin, GPL-3.0 like AMF; repo
6. current wip mods\\MO2ModlistManager, MO2ModlistManager.py) - (pattern, leaf, weight) - read straight from its source
and written out as C++. Its fine-grained leaves are folded into the few separators an MCM list wants (LEAF_TO_GROUP).

std::regex (ECMAScript) has no lookbehind, so (?<! ...) guards are dropped: a pattern may then match a little more
widely than in MO2, which is fine for "it doesn't have to be perfect". Re-run this after Modlist Manager's table changes:
    python tools/gen_mcm_categories.py
"""
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
MO2 = os.path.join(os.path.dirname(REPO), "MO2ModlistManager", "MO2ModlistManager.py")
OUT = os.path.join(REPO, "source", "McmCategoryRules.inc")

src = open(MO2, encoding="utf-8").read()
start = src.index("TEXT_SIGNALS = [(re.compile(p, re.I), c, w) for p, c, w in (")
end = src.index("\n)]\n", start)
body = src[src.index("(", src.index(" in (", start) + 3): end + 2]  # the tuple of (pattern, leaf, weight)
consts = {"DEFINITIVE": 3.6, "NAMED_ROW": 6.0, "NAME_DEF": 3.61, "SHAPE_CAT": "Shape"}
rows = eval(body, {}, consts)

# Modlist Manager's leaves folded into MCM separators; (prefix match on the leaf, group key). First match wins.
LEAF_TO_GROUP = [
    ("User Interface", "Interface"), ("UI Overhaul", "Interface"), ("Icon Overhauls", "Interface"), ("Maps", "Interface"),
    ("Dialogue", "Interface"),
    ("Improved Controls", "Controls"),
    ("Camera", "Camera"),
    ("Gameplay - Combat", "Combat"), ("Animation - Combat", "Combat"),
    ("Animation", "Animation"),
    ("Magic", "MagicSkills"), ("Class, Perks", "MagicSkills"), ("Shouts", "MagicSkills"),
    ("Body", "Characters"), ("Face", "Characters"), ("Hair", "Characters"), ("Races", "Characters"), ("Physics", "Characters"),
    ("Player", "Characters"), ("Shape", "Characters"), ("Equipment Positioning", "Characters"),
    ("NPC", "NpcsCreatures"), ("Creatures", "NpcsCreatures"),
    ("Audio", "Audio"),
    ("Quests", "QuestsPlaces"), ("Player homes", "QuestsPlaces"), ("Dungeons", "QuestsPlaces"), ("Locations - New", "QuestsPlaces"),
    ("Guilds", "QuestsPlaces"),
    ("Environment", "WorldVisuals"), ("Lighting", "WorldVisuals"), ("Visual Effects", "WorldVisuals"), ("Presets", "WorldVisuals"),
    ("Mesh", "WorldVisuals"), ("Models and Textures", "WorldVisuals"), ("PBR", "WorldVisuals"), ("Collision", "WorldVisuals"),
    ("Buildings", "WorldVisuals"), ("Location Overhauls", "WorldVisuals"), ("Cubemaps", "WorldVisuals"),
    ("Items and Objects", "WorldVisuals"),
    ("Gameplay", "Gameplay"), ("Immersion", "Gameplay"), ("Alchemy", "Gameplay"), ("Crafting", "Gameplay"),
    ("Enchanting", "Gameplay"), ("Overhauls", "Gameplay"), ("Cheats", "Gameplay"), ("Clothing", "Gameplay"),
    ("New ", "Gameplay"), ("Armour", "Gameplay"), ("Weapons", "Gameplay"),
    ("Frameworks", "Utility"), ("Utilities", "Utility"), ("Bug Fixes", "Utility"), ("Essential Engine Fixes", "Utility"),
    ("Debugging", "Utility"), ("Script Fixes", "Utility"), ("SKSE", "Utility"), ("Mesh and Texture Fixes", "Utility"),
    ("Unofficial", "Utility"), ("Performance", "Utility"), ("Patches", "Utility"), ("Alternate Start", "Utility"),
    ("Save Games", "Utility"),
]


def group_of(leaf):
    for prefix, group in LEAF_TO_GROUP:
        if leaf.startswith(prefix):
            return group
    raise SystemExit(f"no MCM group for Modlist Manager leaf {leaf!r} - add it to LEAF_TO_GROUP")


def strip_lookbehind(p):
    # (?<!...) and (?<=...) groups, which may hold nested parentheses-free alternatives in this table
    out, i = [], 0
    while i < len(p):
        if p.startswith("(?<!", i) or p.startswith("(?<=", i):
            depth, j = 0, i
            while j < len(p):
                if p[j] == "\\":
                    j += 2
                    continue
                if p[j] == "(":
                    depth += 1
                elif p[j] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            i = j + 1
            continue
        out.append(p[i])
        i += 1
    return "".join(out)


def cpp_raw(s):
    assert ')"' not in s
    return 'R"(' + s + ')"'


commit = subprocess.run(["git", "-C", os.path.dirname(MO2), "log", "-1", "--format=%h"], capture_output=True, text=True).stdout.strip()
lines = [
    "// GENERATED by tools/gen_mcm_categories.py - do not edit by hand; re-run the script instead.",
    f"// Source: MO2 Modlist Manager's TEXT_SIGNALS (our own plugin, GPL-3.0), MO2ModlistManager.py @ {commit}.",
    "// Each row: a name pattern (std::regex, ECMAScript, case-insensitive; lookbehinds dropped), the MCM group it votes",
    "// for, and its weight. The highest summed group wins; no vote at all is \"Other\".",
]
for pattern, leaf, weight in rows:
    p = strip_lookbehind(pattern)
    lines.append(f'{{ {cpp_raw(p)}, "{group_of(leaf)}", {float(weight)}f }},  // {leaf}')
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"{len(rows)} rules written to {OUT}")
